Features
philn123/RPG_Unity pull request #4
Opened 2020-02-28 21:08 UTC by philn123

I added a basic controls menu at the start of the game. I have a quest npc that has two quests and they are tracked when you accept them.

2020-03-02 18:24 UTC, randymester requested changes
Your code and logic look good, you just have to clean it up

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Controllers/EventManager.cs
> +    //private QuestGiver questGiver = null;
Remove unneeded comments

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Controllers/EventManager.cs
> +
Clean up spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Controllers/PlayerController.cs
Clean up spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Controllers/PlayerController.cs
Clean up spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Interactable.cs
>      }
Remove debugging elements in final product. You could alternatively use the unity preprocessor directive "if UNITY_EDITOR"

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/Inventory/Inventory.cs
Clean up spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/ControlsUI.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/ControlsUI.cs
> +    // Update is called once per frame
Remove unneeded comments and boilerplate comments

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/ControlsUI.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +    // Start is called before the first frame update
Remove comment

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +    public static PlayerJournal instance;
Initialize this

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +        }
-Debug logs should only be present in Unity Editor, see previous comment
-Also, if there is more than one instance, don't we want to destroy the new one if this is a singleton?

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +    private Dictionary<QuestType, QuestItemController> controllers;
Move this field declaration up with the other fields. Also initialize it

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +    // Update is called once per frame
Spacing and delete boilerplate comments

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +        //Debug.Log(PlayerQuests[0].Title);
Remove commented out code or add a preprocessor directive around this

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +    public void OnActionCompleted(QuestType questType)
Add a space between these

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/PlayerJournal.cs
> +            }
Refer to previous debug log comments

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Remove unused fields

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +    //need to open a panel that loads those quests
What is this a comment for? Put comments directly above what they are referring to

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Remove commented out code

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestGiver.cs
> +
Spacing

2020-03-02 18:24 UTC, randymester commented on Assets/Scripts/New Features/QuestItemController.cs
> +    public TextMeshProUGUI ProgressText;
Initialize all fields

2020-03-03 19:14 UTC, philn123 commented
Hey Randy, I pushed the changes that you requested

On Mon, Mar 2, 2020, 10:24 AM randymester <notifications@github.com> wrote:

> *@randymester* requested changes on this pull request.
>
> Your code and logic look good, you just have to clean it up
> ------------------------------
>
> In Assets/Scripts/Controllers/EventManager.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386548378>:
>
> > +    //[SerializeField]
>
> +    //private QuestGiver questGiver = null;
>
>
> Remove unneeded comments
> ------------------------------
>
> In Assets/Scripts/Controllers/EventManager.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386548535>:
>
> > +
>
> +
>
>
> Clean up spacing
> ------------------------------
>
> In Assets/Scripts/Controllers/PlayerController.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386548924>:
>
> >
>
>
>
>
> Clean up spacing
> ------------------------------
>
> In Assets/Scripts/Controllers/PlayerController.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386548972>:
>
> > @@ -26,8 +26,6 @@ void Update()
>
>          }
>
>
>
>
>
> -
>
> -
>
>          if(Input.GetMouseButtonDown(1)){
>
>
>
>
> Clean up spacing
> ------------------------------
>
> In Assets/Scripts/Interactable.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386552813>:
>
> >      public virtual void Interact(){
>
>          //method is going to be overwritten\
>
> -        //Debug.Log("Interacting with " + transform.name);
>
> +        Debug.Log("Interacting with " + transform.name);
>
>      }
>
>
> Remove debugging elements in final product. You could alternatively use
> the unity preprocessor directive "if UNITY_EDITOR"
> ------------------------------
>
> In Assets/Scripts/Inventory/Inventory.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386552972>:
>
> > +
>
>
>
>
> Clean up spacing
> ------------------------------
>
> In Assets/Scripts/New Features/ControlsUI.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386553284>:
>
> > @@ -0,0 +1,24 @@
>
> +﻿using System.Collections;
>
> +using System.Collections.Generic;
>
> +using UnityEngine;
>
> +
>
> +public class ControlsUI : MonoBehaviour
>
> +{
>
> +
>
>
> Spacing
> ------------------------------
>
> In Assets/Scripts/New Features/ControlsUI.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386553560>:
>
> > +    // Start is called before the first frame update
>
> +    //void Start()
>
> +    //{
>
> +
>
> +    //}
>
> +
>
> +    // Update is called once per frame
>
>
> Remove unneeded comments and boilerplate comments
> ------------------------------
>
> In Assets/Scripts/New Features/ControlsUI.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386553622>:
>
> > +
>
> +    public GameObject controlsUI;
>
> +    // Start is called before the first frame update
>
> +    //void Start()
>
> +    //{
>
> +
>
> +    //}
>
> +
>
> +    // Update is called once per frame
>
> +    void Update()
>
> +    {
>
> +        if (Input.GetButtonDown("Controls"))
>
> +        {
>
> +            controlsUI.SetActive(!controlsUI.activeSelf);
>
> +        }
>
> +
>
>
> Spacing
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386553787>:
>
> > @@ -0,0 +1,93 @@
>
> +﻿using System.Collections;
>
> +using System.Collections.Generic;
>
> +using UnityEngine;
>
> +
>
> +public class PlayerJournal : MonoBehaviour
>
> +{
>
> +
>
>
> Spacing
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386554114>:
>
> > @@ -0,0 +1,93 @@
>
> +﻿using System.Collections;
>
> +using System.Collections.Generic;
>
> +using UnityEngine;
>
> +
>
> +public class PlayerJournal : MonoBehaviour
>
> +{
>
> +
>
> +    private const string progressFormat = "{0}/{1}";
>
> +
>
> +    [SerializeField]
>
> +    private GameObject playerJournal = null;
>
> +    // Start is called before the first frame update
>
>
> Remove comment
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386558964>:
>
> > +    private const string progressFormat = "{0}/{1}";
>
> +
>
> +    [SerializeField]
>
> +    private GameObject playerJournal = null;
>
> +    // Start is called before the first frame update
>
> +
>
> +    public List<Quest> PlayerQuests = null;
>
> +
>
> +    [SerializeField]
>
> +    private GameObject panel = null;
>
> +
>
> +    [SerializeField]
>
> +    private GameObject questItemPrefab = null;
>
> +
>
> +    #region Singleton
>
> +    public static PlayerJournal instance;
>
>
> Initialize this
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386559712>:
>
> > +        if (instance != null)
>
> +        {
>
> +            Debug.LogWarning("More than one instance");
>
> +            return;
>
> +        }
>
>
> -Debug logs should only be present in Unity Editor, see previous comment
> -Also, if there is more than one instance, don't we want to destroy the
> new one if this is a singleton?
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386560253>:
>
> > +            return;
>
> +        }
>
> +        instance = this;
>
> +        PlayerQuests = new List<Quest>();
>
> +
>
> +        playerJournal.SetActive(false);
>
> +
>
> +        controllers = new Dictionary<QuestType, QuestItemController>()
>
> +        {
>
> +            { QuestType.Combat, null },
>
> +            { QuestType.Fetch, null },
>
> +        };
>
> +    }
>
> +    #endregion
>
> +
>
> +    private Dictionary<QuestType, QuestItemController> controllers;
>
>
> Move this field declaration up with the other fields. Also initialize it
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386560366>:
>
> > +
>
> +
>
> +
>
> +    // Update is called once per frame
>
>
> Spacing and delete boilerplate comments
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386560419>:
>
> > +        };
>
> +    }
>
> +    #endregion
>
> +
>
> +    private Dictionary<QuestType, QuestItemController> controllers;
>
> +
>
> +
>
> +
>
> +    // Update is called once per frame
>
> +    void Update()
>
> +    {
>
> +        if(Input.GetButtonDown("Journal"))
>
> +        {
>
> +            playerJournal.SetActive(!playerJournal.activeSelf);
>
> +        }
>
> +
>
>
> Spacing
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386560716>:
>
> > +
>
> +
>
> +    // Update is called once per frame
>
> +    void Update()
>
> +    {
>
> +        if(Input.GetButtonDown("Journal"))
>
> +        {
>
> +            playerJournal.SetActive(!playerJournal.activeSelf);
>
> +        }
>
> +
>
> +    }
>
> +
>
> +    public void Add(Quest quest)
>
> +    {
>
> +        PlayerQuests.Add(quest);
>
> +        //Debug.Log(PlayerQuests[0].Title);
>
>
> Remove commented out code or add a preprocessor directive around this
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386561478>:
>
> > +    }
>
> +    public void OnActionCompleted(QuestType questType)
>
>
> Add a space between these
> ------------------------------
>
> In Assets/Scripts/New Features/PlayerJournal.cs
> <https://github.com/philn123/RPG_Unity/pull/4#discussion_r386561762>:
>
> > +
>
> +            }
>
> +
>
> +        }
>
> +
>
> +    }
>
> +
>
>
> Spacing
> ------------------------------
>
> In Assets/Scripts/New Featur [...]

2020-03-04 17:10 UTC, randymester approved these changes

2020-03-04 17:10 UTC, merged